services:
  server:
    build: .
    image: duynguyen03/audio-server:v2
    container_name: audio-server
    ports:
      - "9876:9876/udp"
    networks:
      - server-network
networks:
  server-network:
    driver: bridge